# Generated by Django 2.2.4 on 2020-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200918_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='edit',
            field=models.CharField(default='Edit', max_length=255),
        ),
    ]
