# Generated by Django 2.2.4 on 2020-09-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_edit',
            field=models.CharField(default='Edit_test', max_length=255),
        ),
    ]
